- name: Ensures that yum-cron package is installed
  tags: yum-cron
  yum:
    name: yum-cron
    state: latest
    update_cache: yes
  register: yum_cron_yum

- block:
    - name: Applying yum-cron configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart yum-cron
      with_items:
        - { src: yum-cron.conf.j2, dst: /etc/yum/yum-cron.conf }
        - { src: yum-cron-hourly.conf.j2, dst: /etc/yum/yum-cron-hourly.conf }

    - name: Enable and start yum-cron service
      service:
        enabled: yes
        name: yum-cron
        state: started
  tags: yum-cron
  when: yum_cron_yum|success
